import random
from typing import Optional
from .constants import Constants
from .directed_graph import DirectedGraph, CyclicGraphError, Vertex, Edge
from .operation import Operation, OperationType
from .schedule import Schedule


class ScheduleGenerator:
    @classmethod
    def _next_generated_item_name(cls, item_counter: int) -> str:
        
        """
        Pick the next data item name as a label for a conflict graph edge.

        Parameters:
        -----------
        item_counter: int
            The number of items generated so far, used to determine the next name.

        Returns:
        --------
        A string representing the next data item name, using single letters for the first 26 items
        """

        if item_counter < len(Constants.LETTERS):
            return Constants.LETTERS[item_counter]
        return f"X{item_counter}"

    @classmethod
    def _collect_induced_conflict_edges(
        cls,
        operations: list[tuple[int, bool, str]]
    ) -> set[tuple[int, int]]:
        
        """
        Given a list of operations (tx_id, is_write, item), collect all induced conflict edges
        between transactions.

        Parameters:
        -----------
        operations: list[tuple[int, bool, str]]
            A list of operations, where each operation is a tuple (tx_id, is_write, item).

        Returns:
        --------
        A set of tuples representing the induced conflict edges between transactions.

        A conflict edge (tx1, tx2) exists if there is a pair of operations on the same item where
        at least one is a write, and the operations are from different transactions.

        This function is used to check if a data item name can be safely reused for multiple edges
        of the conflict graph without introducing new conflict edges that are not in the original graph.
        """

        induced_edges = set()
        for i in range(len(operations)):
            tx1, is_write1, item1 = operations[i]
            for j in range(i + 1, len(operations)):
                tx2, is_write2, item2 = operations[j]
                if tx1 == tx2 or item1 != item2:
                    continue
                if is_write1 or is_write2:
                    induced_edges.add((tx1, tx2))
        return induced_edges

    @classmethod
    def _build_operations_for_assignment(
        cls,
        graph: DirectedGraph,
        edge_items: dict[tuple[int, int], str],
        mode: str,
        must_read_written: bool,
        must_write_read: bool
    ) -> list[tuple[int, bool, str]]:
        """
        Build a list of operations for a given edge item assignment.

        Parameters:
        -----------
        graph: DirectedGraph
            The conflict graph for which we are building operations.
        edge_items: dict[tuple[int, int], str]
            A mapping from graph edges (source, target) to assigned data item names.
        mode: str
            The mode of operation, either "acyclic" or "cyclic".
        must_read_written: bool
            A flag indicating whether a transaction must read an item before writing it.
        must_write_read: bool
            A flag indicating whether a transaction must write an item before reading it.

        Returns:
        --------
        A list of operations, where each operation is a tuple (tx_id, is_write, item).

        Remarks:
        --------
        This function generates a sequence of operations (reads and writes) for each transaction
        based on the assigned edge items. The generated operations respect the constraints
        specified by the `must_read_written` and `must_write_read` flags.

        The difference between "acyclic" and "cyclic" modes is in how the operations are ordered.
        In "acyclic" mode, a topological ordering of the transactions is used to ensure that all
        operations of a transaction appear after the operations of its predecessors in the graph.
        In "cyclic" mode, operations are generated by iterating through the edges without a
        guaranteed global ordering, which may be necessary when the graph contains cycles.
        """


        operations: list[tuple[int, bool, str]] = []

        if mode == "acyclic":
            ordering = graph.topological_sort()

            reads_by_tx = {tx: set() for tx in graph.vertices}
            writes_by_tx = {tx: set() for tx in graph.vertices}

            incoming_by_tx = {tx: [] for tx in graph.vertices}
            for (source, target), item_name in edge_items.items():
                incoming_by_tx[target].append(item_name)

            for tx in ordering:
                incoming_items = sorted(incoming_by_tx[tx])
                outgoing_items = sorted(
                    edge_items[(tx, target)]
                    for target in graph.adjacency[tx]
                    if (tx, target) in edge_items
                )

                for item_name in sorted(incoming_by_tx[tx]):
                    operations.append((tx, False, item_name))  # READ
                    reads_by_tx[tx].add(item_name)

                if must_write_read:
                    for item_name in incoming_items:
                        if item_name in outgoing_items or item_name in writes_by_tx[tx]:
                            continue
                        operations.append((tx, True, item_name))
                        writes_by_tx[tx].add(item_name)

                for item_name in outgoing_items:
                    if must_read_written and item_name not in reads_by_tx[tx]:
                        operations.append((tx, False, item_name))
                        reads_by_tx[tx].add(item_name)
                    operations.append((tx, True, item_name))   # WRITE
                    writes_by_tx[tx].add(item_name)

            return operations

        if mode == "cyclic":
            reads_by_tx = {tx: set() for tx in graph.vertices}
            writes_by_tx = {tx: set() for tx in graph.vertices}

            for (source, target), item_name in sorted(edge_items.items()):
                if must_read_written and item_name not in reads_by_tx[source]:
                    operations.append((source, False, item_name))
                    reads_by_tx[source].add(item_name)

                operations.append((source, True, item_name))   # WRITE
                writes_by_tx[source].add(item_name)

                operations.append((target, False, item_name))  # READ
                reads_by_tx[target].add(item_name)

                if must_write_read and item_name not in writes_by_tx[target]:
                    operations.append((target, True, item_name))
                    writes_by_tx[target].add(item_name)

            return operations

        raise ValueError(f"Unsupported edge assignment mode: {mode}")

    @classmethod
    def _assign_edge_items(cls, graph: DirectedGraph, mode: str) -> dict[tuple[int, int], str]:
        """
        Assign data item names to each edge in the conflict graph.
        
        Parameters:
        -----------
        graph: DirectedGraph
            The conflict graph for which we are assigning edge items.
        mode: str
            The mode of operation, either "acyclic" or "cyclic", which may affect how items can be reused.
        
        Returns:
        --------
        A dictionary mapping each edge (source, target) to a data item name (str).
        
        Remarks:
        --------
        The assignment tries to minimize the number of unique data items used across all edges.
        It does this by attempting to reuse previously assigned data items for new edges, while
        ensuring that the induced conflict edges from the operations do not introduce any new
        edges that are not in the original graph. If no safe reuse is possible, a new unique
        data item name is generated for the edge.
        """
        
        edge_items: dict[tuple[int, int], str] = {}
        item_counter = 0
        generated_items_in_order: list[str] = []

        graph_edges = set(graph.edges.keys())

        for source in graph.vertices:
            for target in graph.adjacency[source]:
                edge = graph.edges[(source, target)]

                if edge.label is not None:
                    # Preserve explicit labels from the graph.
                    edge_items[(source, target)] = edge.label
                    continue

                chosen_item = None

                # Try to reuse previously generated items first.
                for candidate_item in generated_items_in_order:
                    tentative = edge_items.copy()
                    tentative[(source, target)] = candidate_item
                    is_safe = True
                    for must_read_written in (False, True):
                        for must_write_read in (False, True):
                            operations = cls._build_operations_for_assignment(
                                graph,
                                tentative,
                                mode,
                                must_read_written,
                                must_write_read,
                            )
                            induced_edges = cls._collect_induced_conflict_edges(operations)
                            if not induced_edges.issubset(graph_edges):
                                is_safe = False
                                break
                        if not is_safe:
                            break

                    if is_safe:
                        chosen_item = candidate_item
                        break

                # If no safe reuse exists, create a new item.
                if chosen_item is None:
                    chosen_item = cls._next_generated_item_name(item_counter)
                    item_counter += 1
                    generated_items_in_order.append(chosen_item)

                edge_items[(source, target)] = chosen_item

        return edge_items

    @classmethod
    def _generate_random_directed_graph(
        cls,
        transaction_count: int,
        edge_count: int,
        acyclic: bool,
        cyclic: bool,
        max_attempts: Optional[int],
        failure_message: str,
    ) -> DirectedGraph:
        """Generate a random directed graph with optional acyclic/cyclic constraints."""

        if cyclic and acyclic:
            raise ValueError("Graph cannot be both cyclic and acyclic")

        vertices = [Vertex(id=i, label=i) for i in range(1, transaction_count + 1)]
        graph = DirectedGraph(vertices=vertices)

        added_edges = 0

        if cyclic:
            # Create a random cycle to guarantee cyclicity.
            cycle_length = min(random.randint(2, transaction_count), edge_count)
            cycle_vertices = random.sample(range(1, transaction_count + 1), cycle_length)

            for i in range(cycle_length):
                src = cycle_vertices[i]
                dst = cycle_vertices[(i + 1) % cycle_length]
                graph.add_edge(Edge(source=src, target=dst))

            added_edges = cycle_length

        max_attempts = edge_count * 20 if max_attempts is None else max_attempts
        attempts = 0

        while added_edges < edge_count and attempts < max_attempts:
            attempts += 1
            src = random.randint(1, transaction_count)
            dst = random.randint(1, transaction_count)

            if src == dst:
                continue

            edge = Edge(source=src, target=dst)

            if graph.has_edge(edge):
                continue

            graph.add_edge(edge)

            if acyclic:
                try:
                    graph.topological_sort()
                    added_edges += 1
                except CyclicGraphError:
                    graph.remove_edge(edge)
            else:
                added_edges += 1

        if attempts == max_attempts:
            raise RuntimeError(failure_message)

        return graph

    @classmethod
    def generate_random_precedence_graph(
        cls,
        transaction_count: int = 4,
        edge_count: int = 4,
        acyclic: bool = True,
        cyclic: bool = False,
        max_attempts: int = None
    ) -> DirectedGraph:

        """
        Generate a random precedence graph with the specified number of transactions.
        
        Parameters:
        -----------
        transaction_count: int
            Number of transactions (vertices) in the graph
        edge_count: int
            Number of edges to add to the graph
        acyclic: bool
            If True, keep the graph acyclic
        cyclic: bool
            If True, force the graph to contain at least one cycle
        max_attempts: int
            Maximum attempts to generate the desired graph structure

        Returns:
        --------
        A DirectedGraph representing the precedence graph
        """

        return cls._generate_random_directed_graph(
            transaction_count=transaction_count,
            edge_count=edge_count,
            acyclic=acyclic,
            cyclic=cyclic,
            max_attempts=max_attempts,
            failure_message="Failed to generate acyclic graph within max attempts",
        )

    @classmethod
    def generate_random_wait_for_graph(
        cls,
        transaction_count: int = 4,
        edge_count: int = 4,
        acyclic: bool = True,
        cyclic: bool = False,
        max_attempts: int = None
    ) -> DirectedGraph:

        """
        Generate a random wait-for graph with the specified number of transactions.

        A cycle in a wait-for graph indicates deadlock. Use acyclic=True to guarantee
        no deadlock and cyclic=True to guarantee at least one deadlock cycle.

        Args:
            transaction_count: Number of transactions (vertices) in the graph
            edge_count: Number of edges to add to the graph
            acyclic: If True, keep the graph acyclic
            cyclic: If True, force the graph to contain at least one cycle
            max_attempts: Maximum attempts to generate the desired graph structure
        Returns:
            A DirectedGraph representing the wait-for graph
        """

        return cls._generate_random_directed_graph(
            transaction_count=transaction_count,
            edge_count=edge_count,
            acyclic=acyclic,
            cyclic=cyclic,
            max_attempts=max_attempts,
            failure_message="Failed to generate requested wait-for graph within max attempts",
        )

    @classmethod
    def generate_schedule_from_acyclic_precedence_graph(
        cls,
        graph: DirectedGraph,
        must_read_written: bool = False,
        must_write_read: bool = False
    ) -> Schedule:
        
        """
        Generate a schedule that produces the given precedence graph.

        Parameters:
        -----------
        graph: DirectedGraph
            An acyclic precedence graph where vertices are transaction IDs and edges
            represent precedence
        must_read_written: bool
            If True, ensure each WRITE is preceded by a READ of the same item by the same transaction
        must_write_read: bool
            If True, ensure each READ is followed by a WRITE of the same item by the same transaction

        Returns:
        --------
        A Schedule with read and write operations that produce the same precedence graph

        Remarks:
        --------
        The algorithm:
        1. For each edge (i, j) in the precedence graph, assign a unique data item X_ij
        2. Transaction i will WRITE to X_ij, and transaction j will READ from X_ij
        3. This creates a write-read conflict: i -> j in the precedence graph
        4. Operations are ordered using a linear ordering that respects edges where possible

        When must_read_written is True, every WRITE operation is preceded by a READ of the same item
        by the same transaction (unless that read was already added for an incoming edge).
        When must_write_read is True, every READ operation is followed by a WRITE of the same item
        by the same transaction (unless that write already exists for an outgoing edge).
        """
        operations = []

        # For each edge (i, j), assign a unique data item
        edge_items = cls._assign_edge_items(graph, mode="acyclic")

        # Try topological sort, if it fails (cyclic), use vertex order as-is
        ordering = graph.topological_sort()

        # Track reads/writes already added per transaction to avoid duplicating ops
        reads_by_tx = {tx: set() for tx in graph.vertices}
        writes_by_tx = {tx: set() for tx in graph.vertices}

        # Generate operations based on ordering
        # For each transaction in order:
        #   1. First, READ items from incoming edges
        #   2. Optionally WRITE items for incoming reads (must_write_read)
        #   3. Then, WRITE items for outgoing edges (optionally preceded by a READ)
        for tx1 in ordering:
            # Collect all incoming edges to this transaction
            incoming_items = []
            for tx2 in graph.vertices:
                for target in graph.adjacency[tx2]:
                    if target == tx1:
                        item_name = edge_items[(tx2, tx1)]
                        incoming_items.append(item_name)

            # Add READ operations for incoming edges
            for item_name in sorted(incoming_items):  # Sort for deterministic output
                operations.append(Operation(tx=tx1, op=OperationType.READ, item=item_name))
                reads_by_tx[tx1].add(item_name)

            # Collect all outgoing edges from this transaction
            outgoing_items = []
            for target in graph.adjacency[tx1]:
                item_name = edge_items[(tx1, target)]
                outgoing_items.append(item_name)

            # If required, ensure reads are followed by writes of same item by same tx
            if must_write_read:
                for item_name in sorted(incoming_items):
                    # If this transaction already writes this item as an outgoing item, skip
                    if item_name in outgoing_items or item_name in writes_by_tx[tx1]:
                        continue
                    # Append a write for the read item
                    operations.append(Operation(tx=tx1, op=OperationType.WRITE, item=item_name))
                    writes_by_tx[tx1].add(item_name)

            # Add WRITE operations for outgoing edges
            for item_name in sorted(outgoing_items):  # Sort for deterministic output
                if must_read_written and item_name not in reads_by_tx[tx1]:
                    # Precede the write with a read of the same item by the same transaction
                    operations.append(Operation(tx=tx1, op=OperationType.READ, item=item_name))
                    reads_by_tx[tx1].add(item_name)
                operations.append(Operation(tx=tx1, op=OperationType.WRITE, item=item_name))
                writes_by_tx[tx1].add(item_name)

        return Schedule(id=1, operations=operations)

    @classmethod
    def generate_schedule_from_cyclic_precedence_graph(
        cls,
        graph: DirectedGraph,
        must_read_written: bool = False,
        must_write_read: bool = False
    ) -> Schedule:
        """
        Generate a schedule from a cyclic precedence graph by iterating edges.

        Parameters:
        -----------
        graph: DirectedGraph
            A directed graph (possibly cyclic) where vertices are transaction IDs
        must_read_written: bool
            If True, ensure each WRITE is preceded by a READ of the same item
        must_write_read: bool
            If True, ensure each READ is followed by a WRITE of the same item

        Returns:
        --------
        A Schedule with operations that produce the given precedence graph

        Remarks:
        --------
        For each edge (i, j):
        - Transaction i WRITEs a unique data item X_ij
        - Transaction j READs the same item X_ij
        - This creates a write-read conflict: i -> j
        """
        operations = []
        
        # Track reads/writes per transaction
        reads_by_tx = {tx: set() for tx in graph.vertices}
        writes_by_tx = {tx: set() for tx in graph.vertices}
        
        # Assign unique data items to each edge
        edge_items = cls._assign_edge_items(graph, mode="cyclic")
        
        # Iterate through edges and add operations
        for (source, target), item_name in sorted(edge_items.items()):
            # Add WRITE for source transaction
            if must_read_written and item_name not in reads_by_tx[source]:
                operations.append(Operation(tx=source, op=OperationType.READ, item=item_name))
                reads_by_tx[source].add(item_name)
            
            operations.append(Operation(tx=source, op=OperationType.WRITE, item=item_name))
            writes_by_tx[source].add(item_name)
            
            # Add READ for target transaction
            operations.append(Operation(tx=target, op=OperationType.READ, item=item_name))
            reads_by_tx[target].add(item_name)
            
            # Add WRITE for target if must_write_read is enabled
            if must_write_read and item_name not in writes_by_tx[target]:
                operations.append(Operation(tx=target, op=OperationType.WRITE, item=item_name))
                writes_by_tx[target].add(item_name)
        
        return Schedule(id=1, operations=operations)

    @classmethod
    def generate_schedule_from_wait_for_graph(
        cls,
        graph: DirectedGraph
    ) -> Schedule:
        """
        Generate a randomized schedule with SLOCK/XLOCK and strict 2PL that realizes
        the given wait-for graph during execution.

        For each wait-for edge (i -> j), transaction j first locks an item, then
        transaction i requests an XLOCK on the same item. This introduces the wait edge.

        Strict 2PL is enforced by releasing all locks only at transaction end.

        Args:
            graph: Wait-for graph where vertices are transaction IDs and edges i -> j
                   mean transaction i waits for transaction j.

        Returns:
            A randomized schedule that is legal and strict-2PL.
        """
        operations = []

        # Build per-edge items and randomized holder lock choice.
        edge_defs = []
        item_counter = 0
        for (source, target), edge in graph.edges.items():
            if edge.label is None:
                if item_counter < len(Constants.LETTERS):
                    item_name = f"{Constants.LETTERS[item_counter]}"
                else:
                    item_name = f"X{item_counter}"
            else:
                item_name = edge.label

            # Holder lock can be shared or exclusive; requester uses XLOCK to wait.
            holder_lock = random.choice([OperationType.SLOCK, OperationType.XLOCK])
            edge_defs.append((source, target, item_name, holder_lock))
            item_counter += 1

        # Randomize edge order to keep generated schedules diverse.
        random.shuffle(edge_defs)

        # For each edge e, create two events:
        # A_e: holder acquires lock on item
        # B_e: waiter requests XLOCK on same item (produces wait edge waiter -> holder)
        # Constraint: A_e must happen before B_e.
        event_payload = {}
        successors = {}
        indegree = {}

        for idx, (source, target, item_name, holder_lock) in enumerate(edge_defs):
            a_id = f"A{idx}"
            b_id = f"B{idx}"

            event_payload[a_id] = (target, holder_lock, item_name)
            event_payload[b_id] = (source, OperationType.XLOCK, item_name)

            successors[a_id] = [b_id]
            successors[b_id] = []
            indegree[a_id] = 0
            indegree[b_id] = 1

        # Randomized topological order of events respecting A_e -> B_e constraints.
        event_order = []
        available = [eid for eid, deg in indegree.items() if deg == 0]
        while available:
            chosen = random.choice(available)
            available.remove(chosen)
            event_order.append(chosen)

            for nxt in successors[chosen]:
                indegree[nxt] -= 1
                if indegree[nxt] == 0:
                    available.append(nxt)

        # Keep per-transaction lock ownership to emit strict-2PL unlocks at the end.
        locked_items_by_tx = {tx: [] for tx in graph.vertices}
        seen_items_by_tx = {tx: set() for tx in graph.vertices}
        used_items = {item_name for _, _, item_name, _ in edge_defs}

        for event_id in event_order:
            tx, lock_op, item = event_payload[event_id]

            # Each (tx, item) pair appears once by construction, but guard anyway.
            if item not in seen_items_by_tx[tx]:
                operations.append(Operation(tx=tx, op=lock_op, item=item))
                seen_items_by_tx[tx].add(item)
                locked_items_by_tx[tx].append(item)

            # Add an access operation compatible with the lock to keep schedule meaningful.
            if lock_op == OperationType.SLOCK:
                operations.append(Operation(tx=tx, op=OperationType.READ, item=item))
            else:
                operations.append(Operation(tx=tx, op=OperationType.WRITE, item=item))

        # Ensure all transactions perform at least one lock/access operation.
        idle_txs = [tx for tx in graph.vertices if not seen_items_by_tx[tx]]
        random.shuffle(idle_txs)
        for tx in idle_txs:
            solo_item = f"TX{tx}_SOLO"
            while solo_item in used_items:
                solo_item = f"{solo_item}_X"
            used_items.add(solo_item)

            operations.append(Operation(tx=tx, op=OperationType.XLOCK, item=solo_item))
            operations.append(Operation(tx=tx, op=OperationType.WRITE, item=solo_item))
            seen_items_by_tx[tx].add(solo_item)
            locked_items_by_tx[tx].append(solo_item)

        # Strict 2PL tail: release all held locks at transaction end.
        tx_order = list(graph.vertices.keys())
        random.shuffle(tx_order)

        for tx in tx_order:
            unlock_items = locked_items_by_tx.get(tx, []).copy()
            random.shuffle(unlock_items)
            for item in unlock_items:
                operations.append(Operation(tx=tx, op=OperationType.UNLOCK, item=item))

        return Schedule(id=1, operations=operations)

    @classmethod
    def generate_conflict_equivalent_permutations(
        cls,
        schedule: Schedule,
        max_permutations: Optional[int] = None
    ) -> list[Schedule]:
        """
        Generate all conflict-equivalent permutations of the given schedule.

        Parameters:
        -----------
        schedule: Schedule
            The original schedule to permute
        max_permutations: Optional[int]
            If provided, stop after generating this many permutations

        Returns:
        --------
        A list of Schedules that are conflict-equivalent to the input schedule
        """
        if max_permutations is not None and max_permutations <= 0:
            return []

        ops = schedule.operations
        n = len(ops)

        # Build conflict graph
        graph = schedule.build_conflict_graph()
        indegree = graph.get_in_degree()

        results: list[Schedule] = []

        # Backtracking to enumerate all topological sorts of the partial order
        def backtrack(path: list[int], indeg: list[int], available: list[int]):
            # Early stop if we've reached the requested number of permutations
            if max_permutations is not None and len(results) >= max_permutations:
                return

            if len(path) == n:
                perm_ops = [ops[i] for i in path]
                # Create fresh Operation instances to avoid mutating originals
                perm_ops_copied = [
                    Operation(tx=o.tx, op=o.op, item=o.item) for o in perm_ops
                ]
                results.append(Schedule(id=schedule.id, operations=perm_ops_copied))
                return

            # Iterate over a snapshot of available nodes in deterministic order
            for idx in sorted(available):
                # Early stop check before choosing next
                if max_permutations is not None and len(results) >= max_permutations:
                    return

                # Choose idx
                path.append(idx)
                new_available = available.copy()
                new_available.remove(idx)
                indeg_snapshot = indeg.copy()

                # Decrease indegree of neighbors and add newly available nodes
                for neigh in graph.adjacency[idx]:
                    indeg_snapshot[neigh] -= 1
                    if indeg_snapshot[neigh] == 0:
                        new_available.append(neigh)

                backtrack(path, indeg_snapshot, new_available)

                # Backtrack
                path.pop()

                # Another early stop after backtracking
                if max_permutations is not None and len(results) >= max_permutations:
                    return

        initial_available = [i for i in range(n) if indegree[i] == 0]
        backtrack([], indegree, initial_available)
        
        return results
    
    @classmethod
    def generate_random_conflict_equivalent_permutations(
        cls,
        schedule: Schedule,
        count: int = 10,
        max_attempts: Optional[int] = None
    ) -> list[Schedule]:
        """
        Generate random conflict-equivalent permutations efficiently.
        
        Instead of enumerating all permutations (which can be exponential),
        this method randomly samples topological sorts of the conflict graph.
        This is much faster when there are many possible permutations.
        
        Parameters:
        -----------
        schedule: Schedule
            The original schedule to permute
        count: int
            Number of random permutations to generate
        max_attempts: Optional[int]
            Maximum attempts to find unique permutations (default: count * 100)
            If None, will keep trying until count unique permutations are found

        Returns:
        --------
        A list of up to 'count' unique random conflict-equivalent schedules
        """

        if count <= 0:
            return []
        
        ops = schedule.operations
        n = len(ops)
        
        if n == 0:
            return []

        # Build conflict graph
        graph = schedule.build_conflict_graph()
        base_indegree = graph.get_in_degree()
        
        results: list[Schedule] = []
        seen_permutations: set[tuple[int, ...]] = set()
        
        if max_attempts is None:
            max_attempts = count * 100
        
        attempts = 0
        
        while len(results) < count and attempts < max_attempts:
            attempts += 1
            
            # Generate one random topological sort
            indegree = base_indegree.copy()
            available = [i for i in range(n) if indegree[i] == 0]
            permutation = []
            
            while available:
                # Randomly choose from available nodes
                idx = random.choice(available)
                permutation.append(idx)
                available.remove(idx)
                
                # Update indegrees and available nodes
                for neighbor in graph.adjacency[idx]:
                    indegree[neighbor] -= 1
                    if indegree[neighbor] == 0:
                        available.append(neighbor)
            
            # Check if this permutation is unique
            perm_tuple = tuple(permutation)
            if perm_tuple not in seen_permutations:
                seen_permutations.add(perm_tuple)
                
                # Create the schedule from this permutation
                perm_ops = [ops[i] for i in permutation]
                perm_ops_copied = [
                    Operation(tx=o.tx, op=o.op, item=o.item) for o in perm_ops
                ]
                results.append(Schedule(id=schedule.id, operations=perm_ops_copied))
        
        return results
    
    